export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_COMPLETED = 'REGISTER_USER_COMPLETED';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_COMPLETED = 'LOGIN_USER_COMPLETED';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_COMPLETED = 'LOGOUT_USER_COMPLETED';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_COMPLETED = 'FETCH_USER_COMPLETED';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';
