export const FETCH_WORKER_DEMO = 'FETCH_WORKER_DEMO';
export const FETCH_WORKER_DEMO_COMPLETED = 'FETCH_WORKER_DEMO_COMPLETED';
export const AUTH_DEMO = 'AUTH_DEMO';
export const AUTH_DEMO_COMPLETED = 'AUTH_DEMO_COMPLETED';
