export const FETCH_LEAGUE = 'FETCH_LEAGUE';
export const FETCH_LEAGUE_COMPLETED = 'FETCH_LEAGUE_COMPLETED';
export const CREATE_LEAGUE = 'CREATE_LEAGUE';
export const CREATE_LEAGUE_COMPLETED = 'CREATE_LEAGUE_COMPLETED';
export const JOIN_LEAGUE = 'JOIN_LEAGUE';
export const JOIN_LEAGUE_COMPLETED = 'JOIN_LEAGUE_COMPLETED';
