export const LIKE_POST = 'LIKE_POST';
export const LIKE_POST_COMPLETED = 'LIKE_POST_COMPLETED';
export const DELETE_LIKE_POST = 'DELETE_LIKE_POST';
export const DELETE_LIKE_POST_COMPLETED = 'DELETE_LIKE_POST_COMPLETED';
