export const LIKE_POST = 'LIKE_POST';
export const LIKE_POST_COMPLETED = 'LIKE_POST_COMPLETED';
export const UNLIKE_POST = 'UNLIKE_POST';
export const UNLIKE_POST_COMPLETED = 'UNLIKE_POST_COMPLETED';
