export const CREATE_NOTIFICATION = 'CREATE_NOTIFICATION';
export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const FETCH_NOTIFICATIONS_COMPLETED = 'FETCH_NOTIFICATIONS_COMPLETED';
export const VIEW_NOTIFICATION = 'VIEW_NOTIFICATION';
export const VIEW_NOTIFICATION_COMPLETED = 'VIEW_NOTIFICATION_COMPLETED';
export const VIEW_ALL_NOTIFICATIONS = 'VIEW_ALL_NOTIFICATIONS';
export const VIEW_ALL_NOTIFICATIONS_COMPLETED =
  'VIEW_ALL_NOTIFICATIONS_COMPLETED';
export const DISMISS_NOTIFICATIONS = 'DISMISS_NOTIFICATIONS';
export const DISMISS_NOTIFICATIONS_COMPLETED =
  'DISMISS_NOTIFICATIONS_COMPLETED';
