export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_COMPLETED = 'CREATE_POST_COMPLETED';
export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_COMPLETED = 'DELETE_POST_COMPLETED';
