export const FETCH_TEAM = 'FETCH_TEAM';
export const FETCH_TEAM_COMPLETED = 'FETCH_TEAM_COMPLETED';
export const CLEAR_TEAM = 'CLEAR_TEAM';
export const CLEAR_TEAM_COMPLETED = 'CLEAR_TEAM_COMPLETED';
